# Generated by Django 5.0.2 on 2024-03-12 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
