# Generated by Django 5.0.2 on 2024-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_fooditem_created_at_fooditem_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="image",
            field=models.FileField(upload_to="foodImages"),
        ),
    ]
