# Generated by Django 5.0.2 on 2024-03-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_fooditem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(upload_to="foodImages"),
        ),
    ]
